// <auto-generated />
using Firm_Register.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Firm_Register.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220317035309_addFemalesToDatabase")]
    partial class addFemalesToDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Firm_Register.Data.Males", b =>
                {
                    b.Property<int>("Male_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Male_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Male_Id");

                    b.ToTable("Males");
                });

            modelBuilder.Entity("Firm_Register.Models.Family", b =>
                {
                    b.Property<int>("Family_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Family_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Family_Id");

                    b.ToTable("Family");
                });

            modelBuilder.Entity("Firm_Register.Models.Females", b =>
                {
                    b.Property<int>("Female_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Female_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Female_Id");

                    b.ToTable("Females");
                });
#pragma warning restore 612, 618
        }
    }
}
